Successfully activated service 'com.ubuntuone.SyncDaemon'
Activating service name='com.ubuntuone.Credentials'
Successfully activated service 'com.ubuntuone.Credentials'
Activating service name='com.ubuntu.sso'
Successfully activated service 'com.ubuntu.sso'
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 380, in callback
    self._startRunCallbacks(result)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 488, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 575, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1070, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/ubuntuone-client/ubuntuone/syncdaemon/interaction_interfaces.py", line 1273, in connect
    raise NoAccessToken("got empty credentials.")
ubuntuone.syncdaemon.interaction_interfaces.NoAccessToken: got empty credentials.
Activating service name='com.ubuntu.OneConf'
Successfully activated service 'com.ubuntu.OneConf'
WARNING:oneconf.hosts:Error in loading other_hosts file: [Errno 2] No such file or directory: '/home/nakajima/.cache/oneconf/05ef341ad3564f5ac110e4a1533a529d/other_hosts'
Activating service name='com.ubuntu.sso'
Successfully activated service 'com.ubuntu.sso'
Activating service name='com.ubuntu.sso'
Successfully activated service 'com.ubuntu.sso'

** (zeitgeist-datahub:2083): WARNING **: recent-manager-provider.vala:132: Desktop file for "file:///home/nakajima/%E3%83%80%E3%82%A6%E3%83%B3%E3%83%AD%E3%83%BC%E3%83%89/Epson-LP-M6000-eplaser-jp.ppd" was not found, exec: system-config-printer.py, mime_type: application/octet-stream

** (zeitgeist-datahub:2083): WARNING **: recent-manager-provider.vala:132: Desktop file for "file:///home/nakajima/%E3%83%80%E3%82%A6%E3%83%B3%E3%83%AD%E3%83%BC%E3%83%89/Epson-LP-M6000-eplaser-jp.ppd" was not found, exec: system-config-printer.py, mime_type: application/octet-stream

** (zeitgeist-datahub:2083): WARNING **: recent-manager-provider.vala:132: Desktop file for "file:///home/nakajima/%E3%83%80%E3%82%A6%E3%83%B3%E3%83%AD%E3%83%BC%E3%83%89/Epson-LP-M6000-eplaser-jp.ppd" was not found, exec: system-config-printer.py, mime_type: application/octet-stream

(gnome-screensaver:1852): Gtk-CRITICAL **: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(gnome-screensaver:1852): Gtk-CRITICAL **: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(gnome-screensaver:1852): Gtk-CRITICAL **: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(gnome-screensaver:1852): Gtk-CRITICAL **: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(gnome-screensaver:1852): Gtk-CRITICAL **: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(gnome-screensaver:1852): Gtk-CRITICAL **: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(gnome-screensaver:1852): Gtk-CRITICAL **: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(gnome-screensaver:1852): Gtk-CRITICAL **: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(gnome-screensaver:1852): Gtk-CRITICAL **: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(gnome-screensaver:1852): Gtk-CRITICAL **: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(gnome-screensaver:1852): Gtk-CRITICAL **: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(gnome-screensaver:1852): Gtk-CRITICAL **: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(gnome-screensaver:1852): Gtk-CRITICAL **: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed

** (zeitgeist-datahub:2083): WARNING **: recent-manager-provider.vala:132: Desktop file for "file:///home/nakajima/%E3%83%80%E3%82%A6%E3%83%B3%E3%83%AD%E3%83%BC%E3%83%89/Epson-LP-M6000-eplaser-jp.ppd" was not found, exec: system-config-printer.py, mime_type: application/octet-stream

** (zeitgeist-datahub:2083): WARNING **: recent-manager-provider.vala:132: Desktop file for "file:///home/nakajima/%E3%83%80%E3%82%A6%E3%83%B3%E3%83%AD%E3%83%BC%E3%83%89/Epson-LP-M6000-eplaser-jp.ppd" was not found, exec: system-config-printer.py, mime_type: application/octet-stream
module-cache-reaper-Message: Reaping abandoned data directories
module-cache-reaper-Message: Reaping abandoned cache directories
Activating service name='com.ubuntu.OneConf'
Successfully activated service 'com.ubuntu.OneConf'
WARNING:oneconf.hosts:Error in loading other_hosts file: [Errno 2] No such file or directory: '/home/nakajima/.cache/oneconf/05ef341ad3564f5ac110e4a1533a529d/other_hosts'
Activating service name='com.ubuntu.sso'
Successfully activated service 'com.ubuntu.sso'
Activating service name='com.ubuntu.sso'
Successfully activated service 'com.ubuntu.sso'
Activating service name='com.ubuntu.OneConf'
Successfully activated service 'com.ubuntu.OneConf'
WARNING:oneconf.hosts:Error in loading other_hosts file: [Errno 2] No such file or directory: '/home/nakajima/.cache/oneconf/05ef341ad3564f5ac110e4a1533a529d/other_hosts'
Activating service name='com.ubuntu.sso'
Successfully activated service 'com.ubuntu.sso'
Activating service name='com.ubuntu.sso'
Successfully activated service 'com.ubuntu.sso'

** (zeitgeist-datahub:2083): WARNING **: recent-manager-provider.vala:132: Desktop file for "file:///home/nakajima/%E3%83%80%E3%82%A6%E3%83%B3%E3%83%AD%E3%83%BC%E3%83%89/Epson-LP-M6000-eplaser-jp.ppd" was not found, exec: system-config-printer.py, mime_type: application/octet-stream

** (zeitgeist-datahub:2083): WARNING **: recent-manager-provider.vala:132: Desktop file for "file:///home/nakajima/%E3%83%80%E3%82%A6%E3%83%B3%E3%83%AD%E3%83%BC%E3%83%89/Epson-LP-M6000-eplaser-jp.ppd" was not found, exec: system-config-printer.py, mime_type: application/octet-stream
Activating service name='com.canonical.Unity.Scope.Home'
Successfully activated service 'com.canonical.Unity.Scope.Home'

(unity-scope-home:8451): unity-scope-home-WARNING **: platform-info.vala:112: Unable to read SIM properties: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.ofono was not provided by any .service files
Activating service name='com.canonical.Unity.Scope.Applications'
Activating service name='com.canonical.Unity.Scope.LocalFiles'
Activating service name='com.canonical.Unity.Scope.File.Gdrive'

(process:8466): unity-files-daemon-WARNING **: folder.vala:65: Failed to read favorites: '/home/nakajima/.gtk-bookmarks' を開けません: そのようなファイルやディレクトリはありません
Successfully activated service 'com.canonical.Unity.Scope.LocalFiles'
Successfully activated service 'com.canonical.Unity.Scope.File.Gdrive'
Successfully activated service 'com.canonical.Unity.Scope.Applications'

** (zeitgeist-datahub:2083): WARNING **: recent-manager-provider.vala:132: Desktop file for "file:///home/nakajima/%E3%83%80%E3%82%A6%E3%83%B3%E3%83%AD%E3%83%BC%E3%83%89/Epson-LP-M6000-eplaser-jp.ppd" was not found, exec: system-config-printer.py, mime_type: application/octet-stream
